# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ece383/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'Final_Project_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/ece383/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'Final_Project_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
