# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ece383/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/Final_Project_frogger1_0_0.xci
# IP: The module: 'Final_Project_frogger1_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: c:/ece383/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/Final_Project_frogger1_0_0.xci
# IP: The module: 'Final_Project_frogger1_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
