# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/ece383/Lab2/Lab2.srcs/constrs_1/imports/lab2_code_for_cadets/Lab2.xdc

# Block Designs: bd/Final_Project/Final_Project.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project || ORIG_REF_NAME==Final_Project} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_microblaze_0_0/Final_Project_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_microblaze_0_0 || ORIG_REF_NAME==Final_Project_microblaze_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_dlmb_v10_0/Final_Project_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_dlmb_v10_0 || ORIG_REF_NAME==Final_Project_dlmb_v10_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_ilmb_v10_0/Final_Project_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_ilmb_v10_0 || ORIG_REF_NAME==Final_Project_ilmb_v10_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_dlmb_bram_if_cntlr_0/Final_Project_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Final_Project_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_ilmb_bram_if_cntlr_0/Final_Project_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Final_Project_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_lmb_bram_0/Final_Project_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_lmb_bram_0 || ORIG_REF_NAME==Final_Project_lmb_bram_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_mdm_1_0/Final_Project_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_mdm_1_0 || ORIG_REF_NAME==Final_Project_mdm_1_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_clk_wiz_1_0/Final_Project_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_clk_wiz_1_0 || ORIG_REF_NAME==Final_Project_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Final_Project_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_mig_7series_0_0/Final_Project_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_mig_7series_0_0 || ORIG_REF_NAME==Final_Project_mig_7series_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_uartlite_0_0/Final_Project_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_uartlite_0_0 || ORIG_REF_NAME==Final_Project_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_smc_0/Final_Project_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_smc_0 || ORIG_REF_NAME==Final_Project_axi_smc_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_util_ds_buf_0_0/Final_Project_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_util_ds_buf_0_0 || ORIG_REF_NAME==Final_Project_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_smc_1_0/Final_Project_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_smc_1_0 || ORIG_REF_NAME==Final_Project_axi_smc_1_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_rst_mig_7series_0_100M_0/Final_Project_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==Final_Project_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_frogger1_0_0/Final_Project_frogger1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_frogger1_0_0 || ORIG_REF_NAME==Final_Project_frogger1_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_xlconstant_0_0/Final_Project_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_xlconstant_0_0 || ORIG_REF_NAME==Final_Project_xlconstant_0_0} -quiet] -quiet

# XDC: c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/Final_Project_ooc.xdc
