# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/ece383/Final_Project/Final_Project.runs/synth_1/Final_Project_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ece383/Final_Project/Final_Project.cache/wt [current_project]
set_property parent.project_path C:/ece383/Final_Project/Final_Project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.2 [current_project]
set_property ip_repo_paths c:/ece383/ip_repo/frogger1_1_0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/ece383/Final_Project/Final_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/hdl/Final_Project_wrapper.vhd
add_files C:/ece383/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/Final_Project.bd
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_microblaze_0_0/Final_Project_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_microblaze_0_0/Final_Project_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_microblaze_0_0/Final_Project_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_dlmb_v10_0/Final_Project_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_ilmb_v10_0/Final_Project_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_dlmb_bram_if_cntlr_0/Final_Project_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_ilmb_bram_if_cntlr_0/Final_Project_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_lmb_bram_0/Final_Project_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_mdm_1_0/Final_Project_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_mdm_1_0/Final_Project_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_clk_wiz_1_0/Final_Project_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_clk_wiz_1_0/Final_Project_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_clk_wiz_1_0/Final_Project_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_clk_wiz_1_100M_0/Final_Project_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_mig_7series_0_0/Final_Project_mig_7series_0_0/user_design/constraints/Final_Project_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_mig_7series_0_0/Final_Project_mig_7series_0_0/user_design/constraints/Final_Project_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_mig_7series_0_0/Final_Project_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_uartlite_0_0/Final_Project_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_uartlite_0_0/Final_Project_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_uartlite_0_0/Final_Project_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_1/bd_04e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_1/bd_04e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_2/bd_04e3_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_3/bd_04e3_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_4/bd_04e3_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_5/bd_04e3_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_6/bd_04e3_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_7/bd_04e3_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_8/bd_04e3_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_9/bd_04e3_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_10/bd_04e3_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_11/bd_04e3_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_12/bd_04e3_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_13/bd_04e3_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_14/bd_04e3_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_15/bd_04e3_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_16/bd_04e3_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_20/bd_04e3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_21/bd_04e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_22/bd_04e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_23/bd_04e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_24/bd_04e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_25/bd_04e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_26/bd_04e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_27/bd_04e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_28/bd_04e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_29/bd_04e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_30/bd_04e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_31/bd_04e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_33/bd_04e3_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_34/bd_04e3_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_35/bd_04e3_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_36/bd_04e3_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_37/bd_04e3_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/bd_0/ip/ip_38/bd_04e3_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_util_ds_buf_0_0/Final_Project_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_util_ds_buf_0_0/Final_Project_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_1/bd_d720_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_1/bd_d720_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_2/bd_d720_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_2/bd_d720_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_3/bd_d720_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_3/bd_d720_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_4/bd_d720_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_5/bd_d720_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_6/bd_d720_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_7/bd_d720_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_8/bd_d720_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_12/bd_d720_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_13/bd_d720_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_14/bd_d720_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_15/bd_d720_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_16/bd_d720_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_17/bd_d720_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_21/bd_d720_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_22/bd_d720_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_23/bd_d720_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_24/bd_d720_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_25/bd_d720_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_26/bd_d720_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_27/bd_d720_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_28/bd_d720_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/bd_0/ip/ip_29/bd_d720_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_smc_1_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_mig_7series_0_100M_0/Final_Project_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_mig_7series_0_100M_0/Final_Project_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_rst_mig_7series_0_100M_0/Final_Project_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_frogger1_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/Final_Project_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ece383/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ece383/Lab2/Lab2.srcs/constrs_1/imports/lab2_code_for_cadets/Lab2.xdc
set_property used_in_implementation false [get_files C:/ece383/Lab2/Lab2.srcs/constrs_1/imports/lab2_code_for_cadets/Lab2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Final_Project_wrapper -part xc7a200tsbg484-1 -incremental_mode off
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Final_Project_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Final_Project_wrapper_utilization_synth.rpt -pb Final_Project_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
