set_property SRC_FILE_INFO {cfile:c:/Users/Grantham.Zimmerman/Desktop/ece383/Lab2/Lab2.gen/sources_1/ip/clk_wiz_1_2/clk_wiz_1/clk_wiz_1_in_context.xdc rfile:../../../../../Lab2.gen/sources_1/ip/clk_wiz_1_2/clk_wiz_1/clk_wiz_1_in_context.xdc id:1 order:EARLY scoped_inst:datapath/Audio_Codec/audiocodec_master_clock} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Grantham.Zimmerman/Desktop/ece383/Lab2/Lab2.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../Lab2.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0/clk_wiz_0_in_context.xdc id:2 order:EARLY scoped_inst:datapath/video_inst/mmcm_adv_inst_display_clocks} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Grantham.Zimmerman/Desktop/ece383/Lab2/Lab2.srcs/constrs_1/imports/lab2_code_for_cadets/Lab2.xdc rfile:../../../../../Lab2.srcs/constrs_1/imports/lab2_code_for_cadets/Lab2.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name datapath/Audio_Codec/audiocodec_master_clock/clk_out1 -source [get_pins datapath/Audio_Codec/audiocodec_master_clock/clk_in1] -edges {1 2 3} -edge_shift {0.000 35.688 71.375} [get_pins datapath/Audio_Codec/audiocodec_master_clock/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name datapath/Audio_Codec/audiocodec_master_clock/clk_out2 -source [get_pins datapath/Audio_Codec/audiocodec_master_clock/clk_in1] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} [get_pins datapath/Audio_Codec/audiocodec_master_clock/clk_out2]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells datapath/Audio_Codec/audiocodec_master_clock]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out3 -source [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_in1] -edges {1 2 3} -edge_shift {4.000 3.000 2.000} [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out3]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out1 -source [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_in1] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out1]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out2 -source [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_in1] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_pins datapath/video_inst/mmcm_adv_inst_display_clocks/clk_out2]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells datapath/video_inst/mmcm_adv_inst_display_clocks]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells datapath/Audio_Codec/audiocodec_master_clock]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells datapath/video_inst/mmcm_adv_inst_display_clocks]
