# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ece383/Lab3/Lab3.srcs/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/design_1_Lab3Component1_1_0_2.xci
# IP: The module: 'design_1_Lab3Component1_1_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1_ooc.xdc

# IP: C:/ece383/Lab3/Lab3.srcs/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/design_1_Lab3Component1_1_0_2.xci
# IP: The module: 'design_1_Lab3Component1_1_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ece383/Lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_Lab3Component1_1_0_2/src/clk_wiz_1/clk_wiz_1_ooc.xdc
